# 明日方舟 日常一条龙（不含肉鸽）

[[tasks]]
name = "开始唤醒"
type = "StartUp"
params = { client_type = "Official", start_game_enabled = true }

[[tasks]]
name = "自动公招"
type = "Recruit"
params = { refresh = false, select = [4, 5], confirm = [3, 4, 5], times = 4, expedite = false }

[[tasks]]
name = "基建换班"
type = "Infrast"
params = { mode = 0, facility = ["Mfg", "Trade", "Power", "Control", "Reception", "Office", "Dorm"], drones = "Money", threshold = 0.3, dorm_trust_enabled = false, reception_message_board = true, reception_clue_exchange = true, reception_send_clue = true }

[[tasks]]
name = "信用购物"
type = "Mall"
params = { visit_friends = true, shopping = true, buy_first = ["招聘许可", "龙门币"], blacklist = ["碳", "家具零件", "加急许可"] }

[[tasks]]
name = "领取奖励"
type = "Award"
params = { award = true, mail = true, recruit = true, orundum = true, mining = true, signinevent = true }

[[tasks]]
name = "刷理智"
type = "Fight"
params = { stage = "1-7", medicine = 0, stone = 0, series = 0, times = 6, report_to_penguin = false }

[[tasks]]
name = "关闭游戏"
type = "CloseDown"
params = { client_type = "Official" }
